#!/usr/bin/env python3

import sys
import psycopg2


if len(sys.argv) < 2:
    print(f"Usage: {sys.argv[0]} DBname")
    sys.exit(1)

db = sys.argv[1]
conn = None

try:
    conn = psycopg2.connect(f"dbname={db}")
    print(conn)
    cur = conn.cursor()
except psycopg2.Error as err:
    print("Database error: ", err)
finally:
    if conn is not None:
        conn.close()
    print("Finished with the database")
