#!/usr/bin/env python3

import sys
import psycopg2


if len(sys.argv) < 3:
    print(f"Usage: {sys.argv[0]} subject term")
    sys.exit(1)

subject = sys.argv[1]
term = sys.argv[2]
conn = None

query = """
select  p.id, p.family, p.given
from    subjects s
        join courses c on s.id = c.subject
        join terms t on c.term = t.id
        join course_enrolments e on e.course = c.id
        join people p on p.id = e.student
where   s.code = %s and t.code = %s
order   by p.family, p.given;
"""

try:
    conn = psycopg2.connect("dbname=uni")
    cur = conn.cursor()
    cur.execute(query, [subject, term])
    students = cur.fetchall()

    # Print out the command line arguments
    print(f"{subject} {term}")

    if not students:
        print("No students")
        sys.exit()

    # See q5 for additional error handling

    for student in students:
        zid = student[0]
        family_name = student[1]
        given_name = student[2]
        print(f"{zid} {family_name}, {given_name}")

except psycopg2.Error as err:
    print("Database error: ", err)
finally:
    if conn:
        conn.close()
